name: Mirror to Codeberg

on:
  push:
    branches: ["main"]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: mirror-repository
        uses: spyoungtech/mirror-action@v0.5.1
        with:
          REMOTE: "https://codeberg.org/gabs/pages.git"
          GIT_USERNAME: gabs
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
